### ISSUE TITLE
支持双向SSL

### ISSUE THREAD

**Issue by ycrxun** [quickmsg/smqtt#13]
支持双向SSL么？

**Comment by 1ssqq1lxr** [comment]
不支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月30日(周六) 上午9:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [quickmsg/smqtt] 支持双向SSL (Issue #13)




 
支持双向SSL么？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
