### ISSUE TITLE
smqtt收到的iot数据如何添加个性化处理

### ISSUE THREAD

**Issue by aboluo-gy** [quickmsg/smqtt#7]
smqtt收到的iot数据在保存到内存/DB前如果想进行一些自定义的业务处理应该怎么弄？比如把iot数据做一些过滤，比如iot数据放在rocketmq或者kafka

**Comment by 1ssqq1lxr** [comment]
规则引擎版本还在开发中，项目中有个RecipientRegistry你可以自己拓展下这个接口，通过spi注入进来，可以拿到全量数据。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月2日(周四) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [quickmsg/smqtt] smqtt收到的iot数据如何添加个性化处理 (#7)




 
smqtt收到的iot数据在保存到内存/DB前如果想进行一些自定义的业务处理应该怎么弄？比如把iot数据做一些过滤，比如iot数据放在rocketmq或者kafka
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aboluo-gy** [comment]
好哒
